title: "Nolan Hu"
description: >
  Founder, Hacker, Visionary<br>  
  Like a ghost in the shell, I see beyond the data.
show_downloads: false
google_analytics: "<%= ENV['GOOGLE_ANALYTICS_ID'] %>"
theme: jekyll-theme-hacker

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

custom_repository_url: "https://github.com/iamnolanhu"

github: [metadata]

# Author
author: Nolan Hu

# Permalink structure
permalink: /blog/:year/:month/:day/:title/

# Default frontmatter
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Nolan Hu"
