title: "Nolan Hu"
description: >
  Founder, Hacker, Visionary<br>  
  Like a ghost in the shell, I see beyond the data.
show_downloads: false
theme: jekyll-theme-hacker

custom_repository_url: "https://github.com/iamnolanhu"

github: [metadata]

# Author
author: Nolan Hu

# Permalink structure
permalink: /blog/:year/:month/:day/:title/

# Default frontmatter
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Nolan Hu"

# Collections
collections:
  pages:
    output: true

pages:
  - path: "blog"
    type: "posts"
    output: true
  - path: "projects"
    type: "projects"
    output: true